# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dcd9c1258df42bc34e9154b0eac9442ac1cc699044f44e7700eaeee60dbad5823aa271e6656bc36c50dfead65926a225df2ff11151a417b6efea6e37f955aea

test:
  secret_key_base: 69138223ffd2e109ce8e19d6826846f3918764fe7308e1cabd8292b93805b9434a123336be76409eb3115f54de676e59eafd71aa509e0c4439d1ea5188ccb535

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
